### ISSUE TITLE
Crash when changing tabs via keyboard

### ISSUE THREAD

**Issue by JackLeEmmerdeur** [Mezomish/juffed#100]
Hi. Really like the editor for specific reasons (e.g. counting search-occurrances), but one little bug is keeping me off from using it full-time.

## Bug
If I switch a Tab via CTRL+Tab, the application immediatley crashes.
It then prints "Speicherzugriffsfehler" (Memory access error) on console, without giving any more hints.

## Workaround
Under Settings->Plugins->Key bindings, no key-combination for changing tabs is listed.
Within juffed/src/app/ui/DocViewer.cpp, CTRL+PageUp/PageDown is defined.
Latter key-combination works, but doesn't show the actual document to switch to in a pop-up, like CTRL+Tab.
If I use CTRL+PageUp/PageDown just one time, after application start, the next time I use CTRL+Tab, the app doesn't crash, but it has to be done always after application start.

## More info
Linux MX 17 (Horizon)
Based on Debian 9 (stretch)
XFCE 4.12
Juffed version 0.10

**Comment by q4a** [comment]
@JackLeEmmerdeur Hi. Sorry, I can't reproduce bug. Can you recheck if crash still happens and tell what exact version of package are you using (like juffed 0.10-85-g5ba17f9-9)?

**Comment by JackLeEmmerdeur** [comment]
Hi @q4a!
This wasn't an early April's Joke, right? As you posted on March 30th.
Otherwise it is nice of you to commit to this kind of issues but...my post is more than 4 years old.
I don't think you'll find a significant number of users running those ancient versions of software I mentioned.
Have a nice day.

**Comment by q4a** [comment]
@JackLeEmmerdeur No, it was not joke. I like this text editor and created compare plugin for it, added CI, helped to merge all bug fixes, added few improvements. Recently I joined to contributors team and just start to works with old bug reports: rechecked it, set priorities for fixes / improvements.

**Comment by JackLeEmmerdeur** [comment]
Oh ok. Just wanted to express how impressed I was that one of the main
contributors is taking such care of very old versions. I just couldn't
believe it. But now it makes total sense as the old bugs still could be
there. I've learned something. Thanks for your contributions. CI alone is a
huge plus, if and when it eventually runs.

So regarding your question, I am not sure how to find the version of juffed
back then on MX17. I guess if you can't reproduce this issue, it can be
closed.
