### ISSUE TITLE
Error while loading shared libraries: libjuff.so.0.9

### ISSUE THREAD

**Issue by cloutiy** [Mezomish/juffed#68]
juffed: error while loading shared libraries: libjuff.so.0.9: cannot open shared object file: No such file or directory

Hello, I receive the error above while trying to start Juffed.

I installed as described on your website.

I am on Kubuntu 14.04, however I got the same error on Lubuntu 14.04.

**Comment by unn4m3d** [comment]
Got same error.

I've looked for libjuff in /usr like this
```$ find /usr -type f -name libjuff.*
/usr/lib64/libjuff.so.0.9
#...
```
Then I've set LD_LIBRARY_PATH variable and launched JuffEd:
```
$ LD_LIBRARY_PATH=/usr/lib64 juffed
# Juffed starts as expected
```
But I don't think it's the best solution

**Comment by q4a** [comment]
Fixed long time ago. Last development build for *Ubuntu you can download here: https://github.com/Mezomish/juffed/actions/runs/2061613432
