### ISSUE TITLE
upgrade QT version to 5.x

### ISSUE THREAD

**Issue by zoujiaqing** [Mezomish/juffed#79]
upgrade QT version to 5.x?

**Comment by pvanek** [comment]
cmake ... -DUSE_QT5=1

**Comment by zoujiaqing** [comment]
thank you @pvanek

**Comment by pmattern** [comment]
Yet I wonder why Qt 4 is still default. I mean it has really become a bit rusty by now, hasn't it?

**Comment by pvanek** [comment]
@Mezomish decision is yours ;)

**Comment by q4a** [comment]
"Fixed": https://github.com/Mezomish/juffed/commit/b68ecec7f128bc032b0b4be0098dcf19a56283b2
Now it used QT5 by default.
